// run this function in the console inside the flashcards world site after making the body in the python script
// then run copy(await make_set(body)) in the console to copy to clipboard the link generated by flashcards world
async function makeSet(body) {
    let url = 'https://workerapi.flashcards.world/deck';
    let res = await fetch(url, {method: 'POST', body: JSON.stringify(body)})
    console.log('--res status code: ', res.status);
    let data = await res.json()
    console.log('Flashcard url: ');
    console.log(data);
    return data.link

}
