// original
const res =
    { "cards": [{ "id": "1", "term": "tt1", "def": "dd1", "correctAnswer": 1, "a1": { "answer": "", "isCorrect": true }, "a2": { "answer": "", "isCorrect": false }, "a3": { "answer": "", "isCorrect": false }, "a4": { "answer": "", "isCorrect": false }, "a5": { "answer": "", "isCorrect": false } }, { "id": "2", "term": "tt2", "def": "dd2", "correctAnswer": 1, "a1": { "answer": "", "isCorrect": true }, "a2": { "answer": "", "isCorrect": false }, "a3": { "answer": "", "isCorrect": false }, "a4": { "answer": "", "isCorrect": false }, "a5": { "answer": "", "isCorrect": false } }], "name": "", "desc": "" }

// remake
let body = {
    "cards": [
        { "term": "tt1", "def": "dd1" },
        { "term": "tt2", "def": "dd2"}
    ],
    name: "tst",
    desc: "test desc"

}


const url = 'https://workerapi.flashcards.world/deck'

// run this function in the console inside the flashcards world site after making the body in the python script
// then run copy(await make_set(body)) in the console to copy to clipboard the link generated by flashcards world
async function make_set(body) {
    let url = 'https://workerapi.flashcards.world/deck';
    let res = await fetch(url, {method: 'POST', body: JSON.stringify(body)})
    console.log('--res status code: ', res.status);
    let data = await res.json()
    console.log('Flashcard url: ');
    console.log(data);
    return data.link

}
